### ISSUE TITLE
401 error with new required authentication

### ISSUE THREAD

**Issue by goggledefogger** [casetext/firebase-admin#3]
Firebase is now moving everyone over to Google login, which means the existing way I was using firebase-admin to generate a token no longer works. I was previously using my email and password to login as an admin to Firebase's website, and was using that same email and password with firebase-admin for token generation using FirebaseAdmin.getToken(email, password). But now that I've migrated to logging in with my Google account, using the old email and password now gives me an HTTP 401 error when using FirebaseAdmin.getToken.

I tried using the official firebase-token-generator lib to generate a token, and then tried passing that token to the FirebaseAdmin constructor, but I still get a 401 error. This seems like it should work, right?

Any ideas?

**Comment by goldibex** [comment]
Hi @goggledefogger, thanks for the note.

[Firebase's own firebase-tools](https://github.com/firebase/firebase-tools) now have the ability to generate admin tokens for use with a CI environment.

In the old days, the admin tokens were literally ephemeral -- they were only good for a day. I'm now led to understand they last [between six months and a year](https://github.com/firebase/firebase-tools/issues/85).

As Firebase's own tools in this area have matured, I'm thinking we're going to deprecate every part of `firebase-admin` that duplicates functionality from their side. I'd encourage you to use `firebase-admin` for token generation from this point forward.

Thanks again!

**Comment by goggledefogger** [comment]
Thanks for the response, it worked! I was able to use `firebase-tools` to generate a token, which then worked with the `firebase-admin` constructor.

I still really rely on `firebase-admin` for doing the actual work (updating rules, creating/deleting databases) in Node, so glad it's still available, thanks! It's weird that Firebase hasn't supported that officially, because it's necessary to support basic things like CI and deployment.
