### ISSUE TITLE
auth broken with new Firebase?

### ISSUE THREAD

**Issue by goggledefogger** [casetext/firebase-admin#4]
Now that Firebase got a big redo from Google, I think it may have broken the token auth here? When I try to get a token from the official firebase cli (firebase login:ci) and use it as before with firebase-admin, I now get a 401 error. This was working before, did they change something to deprecate this?

**Comment by daguej** [comment]
Is your firebase instance migrated to the new dashboard?  I wouldn't be surprised if it broke this module.

**Comment by goggledefogger** [comment]
Yes, I did migrate, so I bet that's the problem. I still want the ability to create/delete databases from the CLI, and I don't think the new CLI interface does that. Do you think you'll update your module for the new instances?

**Comment by daguej** [comment]
It's not a priority for us @casetext right now (we haven't migrated yet), but we will need to fix this module before we migrate.

Unfortunately, I can't really give you an ETA on when that might happen.  I'll update here when we plan to look at this.  Alternatively, PR welcome.

**Comment by goggledefogger** [comment]
Great, thanks!

On Wednesday, June 8, 2016, Josh Dague notifications@github.com wrote:

> It's not a priority for us @casetext https://github.com/casetext right
> now (we haven't migrated yet), but we will need to fix this module before
> we migrate.
> 
> Unfortunately, I can't really give you am ETA on when that might happen.
> I'll update here when we plan to look at this. Alternatively, PR welcome.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/casetext/firebase-admin/issues/4#issuecomment-224785760,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABPeWxIhwr1mGUJpd1wtMigKKpAEtcBZks5qJ3sEgaJpZM4IxkG3
> .

## 

Founder / CEO
503-706-8676
https://common-tater.com

**Comment by daguej** [comment]
Update: `firebase-admin` is now published by Google; this repo has nothing to do with the new versions.

We will no longer be maintaining this repo.
